---
- name: Install WordPress, MySQL, Nginx, and PHP-FPM
  hosts: all
  become: yes
  become_method: sudo

  roles:
    - common
    - ufw
    - mariadb
    - php-fpm
    - nginx
    - fail2ban
    - wordpress
