---

- name: Create wordpress user
  user:
    name: '{{ wp_root_user }}'
    home: '{{ wp_root }}'
    groups: '{{ wp_root_group }}'
    shell: /bin/bash


# get wordpress files and db dump

- include: wp-from-local-archives.yml
  when: hostvars['source'] is undefined

- include: wp-from-remote-source.yml
  when: hostvars['source'] is defined


# database

- name: Restore database
  mysql_db:
    name: '{{ wp_db_name }}'
    state: import
    target: /tmp/wordpress.sql.gz

- name: Add mysql user
  mysql_user:
    name: '{{ wp_db_user }}'
    password: '{{ wp_db_password }}'
    priv: 'wordpress.*:ALL'
    state: present


# copy templates and custom files

- name: Copy wp-config.php
  template:
    src: wp-config.php.j2
    dest: '{{ wp_root }}/wp-config.php'
    owner: '{{ wp_root_user }}'
    group: '{{ wp_root_group }}'
    mode: u=rw,g=r,o=

- name: Copy comments.php
  template:
    src: comments.php.j2
    dest: '{{ wp_root }}/wp-content/themes/compost/comments.php'
    owner: '{{ wp_root_user }}'
    group: '{{ wp_root_group }}'
    mode: u=rw,g=r,o=r

- name: Copy functions.php
  template:
    src: functions.php.j2
    dest: '{{ wp_root }}/wp-content/themes/compost/functions.php'
    owner: '{{ wp_root_user }}'
    group: '{{ wp_root_group }}'
    mode: u=rw,g=r,o=r

- name: Copy User Submitted Posts custom form
  copy:
    src: files/usp
    dest: '{{ wp_root }}/wp-content/themes/compost/'


# permissions

- name: Permissions for Wordpress root directory content
  file:
    dest: '{{ wp_root }}'
    owner: '{{ wp_root_user }}'
    group: '{{ wp_root_group }}'
    mode: u=rw,g=r,o=r
    recurse: yes

- name: Permissions for wp-config.php
  file:
    path: '{{ wp_root }}/wp-config.php'
    mode: u=rw,g=r,o=

- name: Permissions for uploads directory content
  file:
    path: '{{ wp_root }}/wp-content/uploads'
    state: directory
    owner: '{{ wp_uploads_user }}'
    group: '{{ wp_uploads_group }}'
    mode: u=rw,g=rw,o=
    recurse: yes

- name: Exec permission for directories
  file:
    path: '{{ wp_root }}'
    mode: u+X,g+X
    recurse: yes


# wp-cli & options

- name: Install WP-CLI
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: '{{ wp_root }}/wp'
    force: true
    owner: wordpress
    group: www-data
    mode: 0700

- name: Set options
  command: ./wp option update {{ item.key }} '{{ item.value }}'
  with_dict: '{{ wp_options_default | combine(wp_options|default({})) }}'
  become_user: '{{ wp_root_user }}'
  args:
    chdir: '{{ wp_root }}'

- name: Set JSON options
  command: ./wp option update {{ item.key }} '{{ item.value }}' --format=json
  with_dict: '{{ wp_options_json_default | combine(wp_options_json|default({})) }}'
  become_user: '{{ wp_root_user }}'
  args:
    chdir: '{{ wp_root }}'

- name: Disable disqus plugin
  command: ./wp plugin deactivate disqus-comment-system
  become_user: '{{ wp_root_user }}'
  args:
    chdir: '{{ wp_root }}'


# cron jobs

- name: Crontab for wordpress scheduled jobs
  cron:
    name: 'wordpress jobs'
    minute: '1-59/10'
    job: './wp cron event run --due-now'
  become: true
  become_user: '{{ wp_root_user }}'

- name: Crontab for minor updates
  cron:
    name: 'wordpress updates'
    hour: '03'
    job: './wp core update --minor && ./wp core update-db; ./wp cli update --patch --yes'
  become: true
  become_user: '{{ wp_root_user }}'


# updates

- name: Update Wordpress
  command: ./wp core update
  become_user: '{{ wp_root_user }}'
  args:
    chdir: '{{ wp_root }}'

- name: Update Wordpress database
  command: ./wp core update-db
  become_user: '{{ wp_root_user }}'
  args:
    chdir: '{{ wp_root }}'

- name: Update Wordpress plugins
  command: ./wp plugin update --all
  become_user: '{{ wp_root_user }}'
  args:
    chdir: '{{ wp_root }}'
