---
users:
  - jacopo
  - piero

server_hostname: hookii.org
legacy_hostname: www.hookii.org www.hookii.it hookii.it

wp_root: /var/www/wordpress
wp_root_user: wordpress
wp_root_group: www-data
wp_uploads_user: www-data
wp_uploads_group: www-data
wp_db_name: wordpress
wp_db_user: wordpress
wp_db_password: '{{ vault_wp_db_password }}'

wp_options_default:
  home: http://{{ server_hostname }}
  siteurl: http://{{ server_hostname }}
  blogname: hookii
  admin_email: wordpress@hookii.org
  usp_email_from: wordpress@hookii.org

wp_options_json_default:
  rt_wp_nginx_helper_options: '{"log_level":"INFO","log_filesize":5,"enable_purge":1,"enable_map":0,"enable_log":0,"enable_stamp":0,"purge_homepage_on_new":1,"purge_homepage_on_edit":1,"purge_homepage_on_del":1,"purge_archive_on_new":1,"purge_archive_on_edit":1,"purge_archive_on_del":1,"purge_archive_on_new_comment":0,"purge_archive_on_deleted_comment":0,"purge_page_on_mod":1,"purge_page_on_new_comment":0,"purge_page_on_deleted_comment":0,"purge_method":"unlink_files","cache_method":"enable_fastcgi","purge_url":"","redis_hostname":"127.0.0.1","redis_port":"6379","redis_prefix":"nginx-cache:"}'
  usp_options: '{"usp_version":20170531,"usp_name":"show","usp_email":"hide","usp_url":"hide","usp_title":"show","usp_tags":"optn","usp_category":"show","usp_content":"show","usp_captcha":"show","usp_recaptcha":"show","usp_images":"hide","usp_form_version":"custom","usp_display_url":"","number-approved":-1,"redirect-url":"","success-message":"Grazie per la segnalazione!","error-message":"Ops, qualcosa deve essere andato storto... Riprova o inviaci la tua segnalazione alla mail ","usp_form_content":"","usp_richtext_editor":1,"categories":["10","11","15","4","13","5","6","9","12","7","14","8"],"usp_use_cat_id":"","author":"1","usp_question":"Quanto fa 10+3 ?","usp_response":"13","recaptcha_public":"","recaptcha_private":"","usp_email_alerts":1,"usp_email_address":"hookiifast@gmail.com","usp_email_from":"wordpress@hookii.org","email_alert_subject":"%%post_title%% | Rapida: 0","email_alert_message":"Nuova segnalazione!\r\nTitolo: %%post_title%%\r\nUrl: %%post_url%%\r\n\r\n####\r\n\r\n","upload-message":"","usp_add_another":"","min-images":0,"max-images":1,"min-image-width":640,"min-image-height":250,"max-image-width":3000,"max-image-height":3000,"auto_display_images":"disable","auto_image_markup":"","auto_email_markup":"","auto_url_markup":"","version_alert":0,"default_options":0,"auto_display_email":null,"auto_display_url":null,"usp_casing":0,"usp_email_html":0,"usp_use_author":0,"usp_use_url":0,"usp_use_cat":0,"usp_include_js":0,"usp_featured_images":0,"disable_required":0,"titles_unique":0,"enable_shortcodes":0,"disable_ip_tracking":0,"logged_in_users":0}'

legacy_account_last_id: 57516
disqus_legacy_shortname: icommentidelpost
disqus_new_shortname: hookii

dumps_dir: ./dumps
wp_old_root: /var/www
wp_db_old_user: wordpressuser
wp_db_old_password: '{{ vault_wp_db_old_password }}'
